In [3]:
from graphNN_hic_likelihood import *

In [4]:
torch.cuda.is_available()

True

In [5]:
device = 'cuda'

In [11]:
train_graphs, train_names, vali_graphs, vali_names, train_loader, vali_loader = \
read_data(
        ["../dataset/train_data_madeup"],
        device=device,
        converage_required_flag=True,
        debug_flag=DEBUG)


Data Loading...
Number of data Loaded: 240
Number of training set: 192
Number of validation set: 48
Number of train data combined: 192
Number of vali data combined: 48


Building training graphs... 
  batch_size: 32
Building vali graphs... 
  batch_size: 32


In [76]:
train_graphs

[DataBatch(x=[528, 74], edge_index=[2, 991], edge_attr=[991, 5], truth=[4592, 4], edge_index_test=[2, 4592], new_node_idx_to_original_idx=[528], batch=[528], ptr=[33]),
 DataBatch(x=[427, 74], edge_index=[2, 658], edge_attr=[658, 5], truth=[3083, 4], edge_index_test=[2, 3083], new_node_idx_to_original_idx=[427], batch=[427], ptr=[33]),
 DataBatch(x=[443, 74], edge_index=[2, 716], edge_attr=[716, 5], truth=[3370, 4], edge_index_test=[2, 3370], new_node_idx_to_original_idx=[443], batch=[443], ptr=[33]),
 DataBatch(x=[425, 74], edge_index=[2, 645], edge_attr=[645, 5], truth=[3022, 4], edge_index_test=[2, 3022], new_node_idx_to_original_idx=[425], batch=[425], ptr=[33]),
 DataBatch(x=[448, 74], edge_index=[2, 714], edge_attr=[714, 5], truth=[3341, 4], edge_index_test=[2, 3341], new_node_idx_to_original_idx=[448], batch=[448], ptr=[33]),
 DataBatch(x=[455, 74], edge_index=[2, 796], edge_attr=[796, 5], truth=[3740, 4], edge_index_test=[2, 3740], new_node_idx_to_original_idx=[455], batch=[455

In [74]:
dataset = CompressedHicFragDataSet(["../dataset/train_data_madeup"], 
                                   coverage_required_flag=True, 
                                   madeup_flag=True, debug_flag=False)

In [75]:
dataset

CompressedHicFragDataSet: 240 samples.

In [49]:
hicMx, fragID, scaffID, \
        names, nFrags, frag_lens, \
        distance_mx, likelihood_mx, frag_coverage, \
        frag_start_loc_relative, frag_masss_center_relative, \
        frag_average_density_global, frag_average_hic_interaction, coverage_flag, \
        repeat_density_flag, frag_repeats_density, total_len_in_pixel = next(iter(dataset))

In [54]:
hicMx.shape, fragID.shape, scaffID.shape

(torch.Size([4, 1024, 1024]), torch.Size([1024]), torch.Size([1024]))

In [56]:
names, nFrags, frag_lens.shape

('chm13_1_normal_numCuts3_numRepeat44', 19, torch.Size([1024]))

In [71]:
frag_lens.shape


torch.Size([1024])

In [72]:
nFrags

19

In [69]:
frag_lens

tensor([156., 464., 111.,  ...,   0.,   0.,   0.])

In [57]:
distance_mx.shape, likelihood_mx.shape, frag_coverage.shape

(torch.Size([2048, 2048]), torch.Size([2048, 2048]), torch.Size([1024]))

In [58]:
frag_start_loc_relative.shape, frag_masss_center_relative.shape

(torch.Size([1024]), torch.Size([1024, 2]))

In [60]:
frag_average_density_global.shape, frag_average_hic_interaction.shape, coverage_flag

(torch.Size([1024, 64]), torch.Size([1024, 1024]), True)

In [62]:
repeat_density_flag, frag_repeats_density.shape, total_len_in_pixel

(True, torch.Size([1024]), tensor(13033, dtype=torch.int32))

In [66]:
distance_mx

tensor([[  0., 156.,  inf,  ...,   0.,   0.,   0.],
        [156.,   0.,  inf,  ...,   0.,   0.,   0.],
        [ inf,  inf,   0.,  ...,   0.,   0.,   0.],
        ...,
        [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
        [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
        [  0.,   0.,   0.,  ...,   0.,   0.,   0.]])

In [ ]:
one_sample_path = f"../dataset/train_data_madeup/{train_names[0][0]}"

In [18]:
one_sample = train_graphs[0][0].cpu()
one_sample

Data(x=[21, 74], edge_index=[2, 46], edge_attr=[46, 5], truth=[210, 4], edge_index_test=[2, 210], new_node_idx_to_original_idx=[21])

In [24]:
mod, optimizer, _, _ = restore_model("./", 'cuda')

Initializing model...



In [29]:
device = torch.device("cuda")

In [30]:
mod = mod.to(device)

In [33]:
res = mod.forward(train_graphs[0][0])

In [35]:
res.shape

torch.Size([210, 4])

In [77]:
one_sample

tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.2281, 0.3134, 0.1005, 0.1380],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.1663, 0.2270, 0.0731, 0.1000],
        [0.0570, 0.0408, 0.1370, 0.0982],
        [0.2878, 0.1003, 0.6899, 0.2410],
        [0.1336, 0.1648, 0.0583, 0.0724],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.1023, 0.0563, 0.2457, 0.1355],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0413, 0.0371, 0.0994, 0.0890],
        [0.0367, 0.0320, 0.0882, 0.0767],
        [0.3062, 0.6623, 0.1349, 0.2914],
        [0.1921, 0.6410, 0.1676, 0.5593],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0